castorini/rank_llm

README.md
pyproject.toml

This version update contains the fix in https://github.com/castorini/rank_llm/pull/15

Bump version 0.0.5 -> 0.0.6

---

README.md
pyproject.toml
rank_llm/estimate_costs.py
rank_llm/pyserini_retriever.py
rank_llm/response_analysis.py
rank_llm/run_rank_llm.py
rank_llm/trec_eval.py

Add current path to sys path to ensure running scripts still work after changing the imports for packaging in https://github.com/castorini/rank_llm/pull/15

Add path for script run

---

demo/rerank_demo_docs.py
demo/rerank_demo_hits.py
rank_llm/rank_gpt.py
rank_llm/rank_vicuna.py
rank_llm/rankllm.py
rank_llm/reranker.py
rank_llm/retrieve_and_rerank.py
rank_llm/retriever.py
rank_llm/run_rank_llm.py

follow up of https://github.com/castorini/rank_llm/pull/23

Implementation of Rerank for RankVicuna

---

r.sh
src/rank_llm/rerank/rank_gpt.py
src/rank_llm/scripts/run_rank_llm.py

ref: https://github.com/castorini/rank_llm/issues/43

variable window size

---

.pre-commit-config.yaml
CONTRIBUTING.md
pr-format.yml

contributing pipeline

---

README.md

readme contribution guidelines

---

src/rank_llm/demo/rerank_rank_gpt.py
src/rank_llm/rerank/api_keys.py
src/rank_llm/retrieve_and_rerank.py

This cl:
1- takes api key into its own module
2- changes the rank_gpt demo and retrieve_and_rerank modules to use this new module

Fix loading api keys

---

src/rank_llm/retrieve/pyserini_retriever.py
src/rank_llm/retrieve/retriever.py

Add argument to pass custom topk to dataset and custom retriever

---

src/rank_llm/demo/rerank_dataset_with_prebuilt_index.py
src/rank_llm/evaluation/trec_eval.py
src/rank_llm/scripts/run_trec_eval.py
test/evaluation/test_trec_eval.py

This cl:
1- adds eval to prebuilt dataset demo
2- applies minor corrections to EvalFunc class and its test
TESTED= the unittest passes, demo runs successfully and the run_trec_eval.py script also runs successfully.

Add eval to prebuilt dataset demo

---

PULL_REQUEST_TEMPLATE.md
pr-format.yml

pr template + automated tests

---

README.md

Quick README.md Update

---

README.md
pyproject.toml
src/rank_llm/demo/rerank_stored_retrieved_results.py

ref: 
- Description: new version release

Release new version, update readme

---

src/rank_llm/api/server.py
src/rank_llm/rerank/identity_reranker.py
src/rank_llm/retrieve/service_retriever.py
src/rank_llm/retrieve_and_rerank.py

Add identity reranker

---

src/rank_llm/rerank/listwise/vicuna_reranker.py
src/rank_llm/rerank/listwise/zephyr_reranker.py
src/rank_llm/rerank/pointwise/pointwise_rankllm.py
src/rank_llm/rerank/reranker.py

This PR fixes rv and rz, after this fix all the demp scripts ran successfully.
ref: N/A
- Description:

fix vicuna and zephyr rerankers, format all

---

src/rank_llm/rerank/reranker.py

fixed bug in extract_kwargs

---

src/rank_llm/rerank/pointwise/pointwise_rankllm.py

Enable heterogeneous top-k for Pointwise Rerankers

---

README.md
pyproject.toml

ref: 
- Description: PyPI update

Update README and PyPI to 0.20.0

---

README.md

Update README.md: Apple Silicon Compatibility

---

README.md
pyproject.toml
src/rank_llm/rerank/listwise/rank_listwise_os_llm.py
src/rank_llm/rerank/rankllm.py
src/rank_llm/rerank/reranker.py
src/rank_llm/retrieve_and_rerank.py
src/rank_llm/scripts/run_rank_llm.py

ref: N/A
- Description: 
1. Install rank_llm locally with `readme.md` instructions
2. Use the following command to run RankZephyr on SGLang
```bash
python src/rank_llm/scripts/run_rank_llm.py  --model_path=castorini/rank_zephyr_7b_v1_full --top_k_candidates=100 --dataset=dl19 --retrieval_method=SPLADE++_EnsembleDistil_ONNX --prompt_mode=rank_GPT  --context_size=4096 --variable_passages --window_size=20 --sglang_batched
```

Add SGLang Support

---

README.md

ref: Error in Installation using pip in AWS Workspace #129
- Description: My diagnosis was right. When I set up RankLLM on the server, nmslib built successfully (the server runs on Linux). Sahel, who also uses Linux, states that there are no problems on her side. However, on all machines with Windows/macOS that I ran on, nmslib failed to build. The person who raised this issue also uses Windows. It appears that this is an OS specific issue.

Update README.md: failed to build nmslib troubleshoot

---

src/rank_llm/rerank/listwise/rank_listwise_os_llm.py

Fix arguments

---

src/rank_llm/rerank/listwise/rank_listwise_os_llm.py

Add RequestOutput Default

---

README.md
pyproject.toml
src/rank_llm/rerank/listwise/rank_listwise_os_llm.py
src/rank_llm/rerank/rankllm.py
src/rank_llm/rerank/reranker.py
src/rank_llm/retrieve/pyserini_retriever.py
src/rank_llm/retrieve_and_rerank.py
src/rank_llm/scripts/run_rank_llm.py

Add TensorRT-LLM Support

---

pyproject.toml
src/rank_llm/rerank/listwise/rank_listwise_os_llm.py

ref: Fix SGLang lockfile issue under /tmp for multiuser accessing the file
https://github.com/sgl-project/sglang/pull/2027
- Description:

Fix SGLang Multiuser issue

---

src/rank_llm/demo/rerank_dataset_with_prebuilt_index.py
src/rank_llm/demo/rerank_inline_hits.py
src/rank_llm/demo/rerank_lit5.py
src/rank_llm/demo/rerank_rank_gpt.py
src/rank_llm/demo/rerank_stored_retrieved_results.py
src/rank_llm/rerank/listwise/lit5_reranker.py
src/rank_llm/rerank/listwise/rank_fid.py

ref: 
- Description:  Lit5_reranker should be on par with all the other rerankers. Added demo for lit5

polish lit5, add lit5 demos

---

README.md
src/rank_llm/demo/rerank_gemini.py
src/rank_llm/rerank/__init__.py
src/rank_llm/rerank/api_keys.py
src/rank_llm/rerank/listwise/__init__.py
src/rank_llm/rerank/listwise/rank_gemini.py
src/rank_llm/rerank/rankllm.py
src/rank_llm/rerank/reranker.py

ref: 
**This is a polished version of PR #162**
- Description:

Gemini Integration

---

README.md
src/rank_llm/analysis/response_analysis.py
src/rank_llm/demo/rerank_gemini.py
src/rank_llm/rerank/listwise/rank_gemini.py
src/rank_llm/rerank/listwise/rank_listwise_os_llm.py
src/rank_llm/rerank/reranker.py

Add rank_gpt prompt support for gemini, minor additional clean ups

---

README.md
src/rank_llm/analysis/response_analysis.py
src/rank_llm/demo/experimental_results.py
src/rank_llm/demo/rerank_firstmistral.py
src/rank_llm/rerank/listwise/rank_gemini.py
src/rank_llm/rerank/listwise/rank_gpt.py

ref: Issue #166 
- Description:

More demos

---

docs/onboarding.md

Update reproduction logs only
Reproduction logs update
6700K, 4090, UW Dragon
| model | dl | ndcg@10 |
|-------|----------|---------|
| RankZephyr | dl20 | 0.8197 |
| E2E FirstMistral | dl20 | 0.7843 |

Docs: Onboarding

---

src/rank_llm/analysis/response_analysis.py
src/rank_llm/demo/experimental_results.py
src/rank_llm/demo/rerank_qwen.py
src/rank_llm/retrieve/pyserini_retriever.py

Add lrl apeer prompt analysis

---

docs/onboarding.md

Google Colab, A100
Results:
| Model  | dl | Metric | 
| ------- | ----| -------|
| RankZephyr | dl20 | 0.8197 |
| E2E First Mistral  | dl20  | 0.7843 |
N/A
- Description:

Docs - Onboarding

---

README.md
pyproject.toml

Pypi release

---

README.md

N/A
This https://github.com/pytorch/pytorch/issues/114602 stops Intel/Rosetta 2 from working, so best not to confuse people in the future.
ref: 

Update macOS compatibility note

---

README.md

ref: issue #39 
- Description:

center the image, add explict anchors for unicode sections

---

README.md

fix the separators

---

docs/onboarding.md

I was able to reproduce the onboarding results on Google Colab (A100 GPU). 
Scores:
FirstMistral: 0.7884
RankZephyr: 0.8200
- Description:

Reproduced onboarding results

---

docs/onboarding.md

UW Basilisk
Results:
Model | dl | Metric
-- | -- | --
RankZephyr | dl20 | 0.8198
E2E First Mistral | dl20 | 0.7885
N/A
- Description:

Add to onboarding reproduction logs

---

PULL_REQUEST_TEMPLATE.md
docs/onboarding.md

Adding to reproduction logs doesn't quite fit into any of the options currently provided by the checklist in PULL_REQUEST_TEMPLATE.md but is a common PR, so I added it as its own option. Also capitalized 'api'.
N/A
- Description:

Update pull request template with 'reproduction' option

---

README.md

update readme with sigir acceptance and arxiv citation

---

src/rank_llm/data.py
src/rank_llm/demo/rank_qwen-r1-distill.py
src/rank_llm/demo/rerank_qwen-r1-distill.py
src/rank_llm/rerank/listwise/listwise_rankllm.py

ref: n/a
- Description: A demo for r1-distill model

Add r1 distill demo and fix receive permutation to preserve original order when an error happens, datawriter supports non-ascii chars

---

src/rank_llm/rerank/inference_handler.py
src/rank_llm/rerank/listwise/listwise_inference_handler.py
src/rank_llm/rerank/listwise/listwise_rankllm.py
src/rank_llm/rerank/listwise/rank_gpt_apeer_template.yaml
src/rank_llm/rerank/listwise/rank_gpt_template.yaml
src/rank_llm/rerank/listwise/rank_listwise_os_llm.py
src/rank_llm/rerank/listwise/rank_lrl_template.yaml
src/rank_llm/rerank/rankllm.py
test/rerank/listwise/test_RankListwiseOSLLM.py

Implemented the functions for ListwiseInferenceHandler and the class to RankListwiseOSLLM
ref: https://github.com/castorini/rank_llm/issues/237
- Description:

Implemented ListwiseInferenceHandler

---

regression_test.sh
src/rank_llm/rerank/reranker.py
src/rank_llm/retrieve_and_rerank.py
src/rank_llm/scripts/run_rank_llm.py

ref: https://github.com/castorini/rank_llm/issues/245
- Description:

Add regression test script and max_queries arg

---

src/rank_llm/rerank/listwise/rank_listwise_os_llm.py
src/rank_llm/scripts/run_rank_llm.py

This allows thinking to be turned off by default if you don't want the model to think, e.g. used for Qwen3 models. 
ref: N/A
- Description:

Allow turning off thinking

---

src/rank_llm/rerank/inference_handler.py
src/rank_llm/rerank/listwise/singleturn_listwise_inference_handler.py

Fix bug in generating prefx and suffix in singleturn inference handler

---

src/rank_llm/analysis/response_analysis.py
src/rank_llm/data.py
src/rank_llm/demo/experimental_results.py
src/rank_llm/rerank/listwise/rank_gemini.py
test/analysis/test_response_analyzer.py

Bug fixes for the experimental_results demo to work

---

.github/workflows/pr-format.yml
.pre-commit-config.yaml
README.md
pyproject.toml

ref: N/A
- Description: new version release

Release v 0.25.0

---

README.md
pyproject.toml
src/rank_llm/demo/experimental_results.py
src/rank_llm/rerank/listwise/lit5_reranker.py
src/rank_llm/rerank/listwise/rank_fid.py
src/rank_llm/rerank/listwise/rank_gemini.py
src/rank_llm/rerank/listwise/rank_gpt.py
src/rank_llm/rerank/listwise/rank_listwise_os_llm.py
src/rank_llm/rerank/listwise/vicuna_reranker.py
src/rank_llm/rerank/listwise/zephyr_reranker.py
src/rank_llm/rerank/pairwise/duot5.py
src/rank_llm/rerank/pointwise/monot5.py

ref: #259
- Description: new version release

Fix yaml paths, update pyproject.toml to include all, new version release

---

README.md
docs/release-notes/release-notes-v0.25.1-v0.25.6.md
docs/release-notes/release-notes-v0.25.6.md

Add release notes for v0.25.1-v0.25.6

---

README.md
pyproject.toml

ref: N/A
- Description:  package release

Bump version 0.25.6 -> 0.25.7

---

README.md

Add news section for important features/updates

---

src/rank_llm/demo/rerank_oss_bright.py
src/rank_llm/demo/rerank_qwen3_bright.py
src/rank_llm/rerank/listwise/rank_listwise_os_llm.py
src/rank_llm/rerank/reranker.py
src/rank_llm/rerank/vllm_handler_with_openai_sdk.py

add vllm inference with open AI API, add demos for bright

---

src/rank_llm/demo/rerank_nemotron_nano_v2.py
src/rank_llm/rerank/listwise/rank_listwise_os_llm.py
src/rank_llm/rerank/prompt_templates/nemotron_nonthinking_template.yaml
src/rank_llm/rerank/prompt_templates/nemotron_thinking_template.yaml
src/rank_llm/rerank/vllm_handler.py

https://github.com/castorini/rank_llm/issues/298
ref: 
- Description: 
cc @sahel-sh 
Results:
~~Non-Thinking:~~
~~BM25 ndcg@10: ndcg_cut_10               all     0.5058~~
~~Rerank ndcg@10: ndcg_cut_10             all     0.6344~~
~~Thinking:~~
~~BM25 ndcg@10: ndcg_cut_10               all     0.5058~~
~~Rerank ndcg@10: ndcg_cut_10             all     0.5143~~
Updated Results:
Thinking:
BM25 ndcg@10: ndcg_cut_10 all 0.5058
Rerank ndcg@10: ndcg_cut_10 all 0.7103
Non-thinking:
BM25 ndcg@10: ndcg_cut_10 all 0.5058
Rerank ndcg@10: ndcg_cut_10 all …

Adding Nvidia Nemotron 9B v2 with VLLM
